### ISSUE TITLE
Can you make the volleyball trained model available?

### ISSUE THREAD

**Issue by nquyen** [shreyas0906/Detecting-Volleyball#1]
Hi Shreyas0906,

I was wondering if you could make your trained volleyball detection model available for use. It is exactly what I am looking for and if I could avoid re-inventing the wheel that would be lovely :)

edit: Specifically your frozen_inference_graph.pb and ball-detect.pbtxt 

Thank you!

**Comment by shreyas0906** [comment]
Hey @nquyen!

I'm really sorry, I don't have it anymore.
